stages:
  data_ingestion:
    cmd: python src\data\data_ingestion.py
    deps:
    - src\data\data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  
  data_preprocessing:
    cmd: python D:\youtube-comment-analyzer-project\youtube-comment-analyzer\src\data\data_preprocessing
    deps:
    - data\raw\train.csv
    - data\raw\test.csv
    - D:\youtube-comment-analyzer-project\youtube-comment-analyzer\src\data\data_preprocessing
    outs:
    - data/interim


  model_building:
    cmd: python D:\youtube-comment-analyzer-project\youtube-comment-analyzer\src\model\model_building.py
    deps:
    - data\interim\train_processed.csv 
    - D:\youtube-comment-analyzer-project\youtube-comment-analyzer\src\model\model_building.py
    params:
    - model_building.max_features
    - model_building.ngram_range
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    
    outs:
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl

  model_evaluation:
    cmd: python D:\youtube-comment-analyzer-project\youtube-comment-analyzer\src\model\model_evaluation.py
    deps:
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - D:\youtube-comment-analyzer-project\youtube-comment-analyzer\src\model\model_evaluation.py
    outs:
    - experiment_info.json